# Generated by Django 5.2.15 on 2026-08-08 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0002_chatsession_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp'], 'verbose_name': 'رسالة', 'verbose_name_plural': 'رسائل المحادثات'},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'جلسة محادثة', 'verbose_name_plural': 'جلسات المحادثة'},
        ),
        migrations.AlterModelOptions(
            name='skinanalysis',
            options={'ordering': ['-created_at'], 'verbose_name': 'تحليل البشرة', 'verbose_name_plural': 'تحليلات البشرة'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'ملف المستخدم', 'verbose_name_plural': 'ملفات المستخدمين'},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/', verbose_name='الصورة المرفقة'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'المريض'), ('ai', 'الذكاء الاصطناعي')], max_length=10, verbose_name='المرسل'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='skincare.chatsession', verbose_name='جلسة المحادثة'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text_content',
            field=models.TextField(blank=True, null=True, verbose_name='نص الرسالة'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='توقيت الرسالة'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ بدء المحادثة'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='نسبة الثقة'),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='ai_prediction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='التشخيص'),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التحليل'),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='image',
            field=models.ImageField(upload_to='skin_images/', verbose_name='صورة البشرة'),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='recommendations',
            field=models.TextField(blank=True, null=True, verbose_name='توصيات إضافية'),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='recommended_products',
            field=models.TextField(blank=True, null=True, verbose_name='المنتجات المقترحة'),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='skin_routine',
            field=models.TextField(blank=True, null=True, verbose_name='الروتين الموصى به'),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='medical_history',
            field=models.TextField(blank=True, null=True, verbose_name='السجل الطبي'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('dry', 'جافة'), ('oily', 'دهنية'), ('mixed', 'مختلطة'), ('sensitive', 'حساسة')], max_length=20, null=True, verbose_name='نوع البشرة'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
